### ISSUE TITLE
Unify language

### ISSUE THREAD

**Issue by vwiedemann** [weiss19ja/amos-ss16-proj2#11]
Our web-interface displays the otions half in german, half in english. We should use one consistent language throughout the whole interface

**Comment by andreas-bauer** [comment]
We could use angular translate to provide some languages, at least german and english.
See https://angular-translate.github.io/

**Comment by uv48uson** [comment]
It depends on the time and effort to include the angular translate, this might be a task for the very last weeks of the project. For now english should be the the frontend language.

**Comment by andreas-bauer** [comment]
It's not a big effort, my estimation for the task size is 5.
