### ISSUE TITLE
Decide on appealing color-scheme

### ISSUE THREAD

**Issue by vwiedemann** [weiss19ja/amos-ss16-proj2#16]
As a user, I want the application to have nice matching colors in the UI.

**Comment by uv48uson** [comment]
We'll receive an email containing the preferred colours of the client.

**Comment by m-hofmann** [comment]
We have received the mail and still need to include the company's colors!

**Comment by vwiedemann** [comment]
Fixed with 2bfd0794fc83dddfec1564a59c159712711eb88c
