### ISSUE TITLE
Mobile client can still control rover when driver is already taken

### ISSUE THREAD

**Issue by vwiedemann** [weiss19ja/amos-ss16-proj2#20]
If a mobile client enters the driver mode and the driver mode is already taken, he can still drive around with the rover even thought the waring is displayed but he can still access the driving dpad.
![screenshot_20160611-134553](https://cloud.githubusercontent.com/assets/15238604/15984921/8e66cf3e-2fdb-11e6-8e26-9d847bff77ae.png)

**Comment by Maximilian-Fischer** [comment]
Ok I reproduced the bug. Seems like the driver mode gets available with a display width of 600 or lower although driver mode should not be available.

**Comment by Maximilian-Fischer** [comment]
Fixed in commit 232f772065b60ab575a2744a4f8cb4cc89875888 on master.
