### ISSUE TITLE
Race condition on site load

### ISSUE THREAD

**Issue by m-hofmann** [weiss19ja/amos-ss16-proj2#23]
Client IDs are assigned too slowly. This leads to an undefined state where a new client can control the rover although it has no driver privileges.

There probably should also be a privilege check in the backend if the driving command was issued by a registered user.

**Comment by Maximilian-Fischer** [comment]
Fixed in commit 6e41c00e9c8ecea00b64d01bb98cbe1e91c2ed8e and merged in master with commit aaaa1aea1042e3c54d28f1a99f19221f6a0eeed2
