### ISSUE TITLE
Connected driver can only acquire driving mode if he is on the main drive page

### ISSUE THREAD

**Issue by vwiedemann** [weiss19ja/amos-ss16-proj2#31]
Acquiring the driving mode only works if the driver uses the /drive view, for /drive/roverMaster for example it doesn't work

**Comment by andreas-bauer** [comment]
fixed in commit c7a53d8a5bbf8aa7cf75616519fa38ac8d4f4132

**Comment by vwiedemann** [comment]
Fixed in commit eeada28c912216af9fd7302f0f6227fb8ca747ad
