### ISSUE TITLE
Both rovers have the same IP

### ISSUE THREAD

**Issue by vwiedemann** [weiss19ja/amos-ss16-proj2#36]
Both rovers use 192.168.0.1 which might cause interference problems (and 192.168.0.1 is also the default address for wifi routers so it might cause problems with them as well)
Solution: Change SSID

**Comment by m-hofmann** [comment]
One Rover has the SSID ROVER the other has the SSID ROVER_NEO. As you can only be connected to one Wi-Fi at a time (usually, edge cases ignored), the rover's IP address should not cause a collision.

**Comment by vwiedemann** [comment]
I wasn't intending to write SSID but IP. Sorry for confusion.

**Comment by m-hofmann** [comment]
Yeah, but as you are only connected to one Wi-Fi at a time I really don't see this as a problem. How is it broken?

**Comment by vwiedemann** [comment]
When I use the desktop it always crashes because the LAN connection also uses 192.168.0.1 for the router. Therefore all Commands that are supposed to go to the rover go to the router and fail. As most of the wifis have 192.168.0.1 as a standard IP, I guess it might fail not only at my place ;)

**Comment by m-hofmann** [comment]
I don't think that being connected to the rover and another device is a real use case for us. But we should ask @uv48uson or @MarkusSchmitz  for clarification.

**Comment by m-hofmann** [comment]
Fixed on both rover's. MK I has IP address `192.168.23.1`, MK II has IP address `192.168.42.1` adjustment was documented in the [wiki](https://github.com/weiss19ja/amos-ss16-proj2/wiki/Configuring-the-wireless-hotspot#operating-with-different-ip-addresses).
