### ISSUE TITLE
Redirect adress isn't changed

### ISSUE THREAD

**Issue by vwiedemann** [weiss19ja/amos-ss16-proj2#38]
When I connect to the rover and try to access bahn.de for example, the rover frontend is displayed but the address is http://bahn.de/ss16/proj2/#/observe which is a bit confusing.

**Comment by m-hofmann** [comment]
This was behavior was the requirement. I'm not sure whether we can implement it any other way without much hassle.

**Comment by vwiedemann** [comment]
Desired behaviour --> won't fix
