### ISSUE TITLE
Firefox Joystick Problem

### ISSUE THREAD

**Issue by vwiedemann** [weiss19ja/amos-ss16-proj2#44]
After letting go of the joystick it doesn't go back to the middle automatically and therefore doesn't stop the rover from driving

**Comment by m-hofmann** [comment]
It seems the mapping of mouse input to the control does not work at all in Firefox. If you click anywhere in the circle of the Joystick, a command is sent but the control is not being redrawn.

**Comment by vwiedemann** [comment]
This bug is caused by joystick initialization, the joystick is loaded over and over again

**Comment by Maximilian-Fischer** [comment]
Fixed with commit c0d9e82e17757a30038c69cdf6497e13c517125d
