### ISSUE TITLE
View is too big on iPad

### ISSUE THREAD

**Issue by vwiedemann** [weiss19ja/amos-ss16-proj2#48]
When having the iPad in vertical mode, the controls are hanging out over the right margin when you're in  Camera & Driving mode or Camera & movement

**Comment by andreas-bauer** [comment]
Fix for this issue caused problems on other mobile devices in "camera & driving" view. 
In portrait mode video stream is not centered and smaller as necessary. 
Camera View and Camera Movement View on mobile devices also show the video stream in a non fitting size.
