### ISSUE TITLE
Save all logging output to file

### ISSUE THREAD

**Issue by m-hofmann** [weiss19ja/amos-ss16-proj2#5]
Right now only communication logs are stored in a file. However, @Maximilian-Fischer and @andreas-bauer would like to have a file containing all logging output produced by the backend application.

**Comment by uv48uson** [comment]
im not sure whether this is the best solution. keep in mind that we have the intention to show the logging file to the admin-user later in the project. therefore it might be easier to have all the logging in one file!? or at least clearer

**Comment by m-hofmann** [comment]
Please clarify what you mean. This task is about storing all logging output in one file and additionally having a communications log.

**Comment by uv48uson** [comment]
ah ok i see. Nevertheless it might be useful to have all (logs and communication) in one file. At least if the backend logs contain somehow interesting information for the user!?

**Comment by m-hofmann** [comment]
I think this is more of a developer related issue.

**Comment by uv48uson** [comment]
Probably. Sry then.
