### ISSUE TITLE
View is broken on Windows Phone

### ISSUE THREAD

**Issue by vwiedemann** [weiss19ja/amos-ss16-proj2#50]
On Windows phone, the buttons don't have labels and you can't see the stream. Also, if you change the view, the client disconnects and reconnects. Not sure whether we can fix that

**Comment by m-hofmann** [comment]
I think Angular Material simply will not run on Windows Phone 8.1 that we have on our testing device. I tested the Angular Material demo page on the device and it was horrible. This is a known [bug](https://github.com/angular/material/issues/1905).
