### ISSUE TITLE
Android can't display frontend of MK I with Opera any more

### ISSUE THREAD

**Issue by vwiedemann** [weiss19ja/amos-ss16-proj2#51]
I can't access the rover website with my android phone. Connecting to ROVER_NEO is working, but I can't access the website in the opera browser
(Has to be tested with other android devices, maybe it's just a problem with mine)

**Comment by m-hofmann** [comment]
The bug was caused by Opera Mini's data saving mechanism that routes every request over Opera's servers. Naturally, our local web server was not reachable that way.
