### ISSUE TITLE
Center Button is too low

### ISSUE THREAD

**Issue by vwiedemann** [weiss19ja/amos-ss16-proj2#53]
Center Button doesn't fit on view on Android with Chrome, you have to scroll down to reach it

**Comment by uv48uson** [comment]
Does this affect the dpads? Are u still able to control the rover via the seemless dpad or might the curser/finger movement then be accounted as scroll?

**Comment by vwiedemann** [comment]
If you have scrolled down, you can use it normally but either you see the full stream or half of the image and the Center button
