### ISSUE TITLE
Socket connection in driver mode opens too late

### ISSUE THREAD

**Issue by vwiedemann** [weiss19ja/amos-ss16-proj2#8]
The first time the head movement is triggered, it occasionally takes some seconds to trigger the movement. Only happens on first movement, probably a problem with the startup-process.

**Comment by vwiedemann** [comment]
The delayed head movement is caused by the socket being opened up too late. The socket opens around 5 seconds after loading the driving mode page.
This is probably caused by the setup-process being triggered too late.

**Comment by Maximilian-Fischer** [comment]
I will work on this bug with andreas this week.I already created a branch for this bug. Our first approach will be to open the socket connection in the main page and already get a client id before we navigate to driving mode.

**Comment by m-hofmann** [comment]
FYI: we could only reproduce this issue with Firefox on @vwiedemann 's system. Chrome works fine.

**Comment by Maximilian-Fischer** [comment]
OK I just recognized that the rover connection gets established pretty fast (less than half a second) with firefox on my developer machine. I think we will test this behavior with the rover as soon as I get one ;)

**Comment by m-hofmann** [comment]
I think we should close this issue then.

**Comment by andreas-bauer** [comment]
On my system with chrome browser connection established immediately.
